import { createHash, randomUUID } from "crypto";
import { buildHeadersWithContentType } from "../fingerprint/manager.js";
import { getTransport } from "../tls/transport.js";
import { getInstallationId } from "./installation-id.js";
import { applyCodexContextHeaders, buildCodexClientMetadata, X_CODEX_WINDOW_ID_HEADER, firstCodexRequestString, nonEmptyString } from "./codex-request-context.js";
import { buildResponsesUpstreamBody } from "./responses-upstream.js";
import { parseSSEStream } from "./codex-sse.js";
import { CodexApiError, type CodexResponsesRequest, type CodexSSEEvent } from "./codex-types.js";
import type { CodexAuxiliaryJsonPath, CodexAuxiliaryRequestContext, UpstreamAdapter } from "./upstream-adapter.js";
const ALLOWED = new Set<CodexAuxiliaryJsonPath>(["alpha/search", "responses/compact", "images/edits"]);
export class CodexResponsesUpstream implements UpstreamAdapter {
  readonly tag = "codex-responses"; readonly baseUrl: string;
  constructor(private readonly apiKey: string, baseUrl: string, private readonly entryId = "anonymous-api-key-entry") { this.baseUrl = baseUrl.replace(/\/+$/, ""); }
  private identity(request: CodexResponsesRequest) { const seed = nonEmptyString(request.prompt_cache_key) ?? nonEmptyString(request.previous_response_id) ?? randomUUID(); const hash = (kind: string, value: string) => `${kind === "conversation" ? "cp" : "cw"}_${createHash("sha256").update(kind).update("\0").update(this.entryId).update("\0").update(value).digest("hex").slice(0, 32)}`; const conversationId = hash("conversation", seed); const window = firstCodexRequestString(request, X_CODEX_WINDOW_ID_HEADER); return { conversationId, windowId: window ? hash("window", window) : `${conversationId}:0` }; }
  private headers(request: CodexResponsesRequest, accept: string, beta: boolean) { const id = this.identity(request); const headers = buildHeadersWithContentType(this.apiKey, null); delete headers["ChatGPT-Account-Id"]; headers.Accept = accept; if (beta) headers["OpenAI-Beta"] = "responses_websockets=2026-02-06"; headers["x-openai-internal-codex-residency"] = "us"; headers["x-client-request-id"] = id.conversationId; headers["x-codex-installation-id"] = getInstallationId(); headers["session-id"] = id.conversationId; headers["thread-id"] = id.conversationId; headers[X_CODEX_WINDOW_ID_HEADER] = id.windowId; applyCodexContextHeaders(headers, request); return { headers, id }; }
  async createResponse(request: CodexResponsesRequest, signal: AbortSignal): Promise<Response> { const { headers, id } = this.headers(request, "text/event-stream", true); const body = buildResponsesUpstreamBody(request, request.model); body.prompt_cache_key = id.conversationId; body.client_metadata = buildCodexClientMetadata(request, getInstallationId(), undefined, id.windowId); const r = await getTransport().post(`${this.baseUrl}/responses`, headers, JSON.stringify(body), signal); if (r.status < 200 || r.status >= 300) throw new CodexApiError(r.status, await r.body?.getReader().read().then(x => x.value ? Buffer.from(x.value).toString() : `HTTP ${r.status}`) ?? `HTTP ${r.status}`, r.headers); return new Response(r.body, { status: r.status, headers: r.headers }); }
  async forwardCodexJsonRequest(path: CodexAuxiliaryJsonPath, body: Record<string, unknown>, signal: AbortSignal, context: CodexAuxiliaryRequestContext = {}): Promise<Response> { if (!ALLOWED.has(path)) throw new CodexApiError(0, `Unsupported Codex auxiliary endpoint: ${path}`); const request: CodexResponsesRequest = { model: typeof body.model === "string" ? body.model : "codex", input: [], stream: true, store: false, ...context }; const { headers } = this.headers(request, "application/json", false); const r = await getTransport().post(`${this.baseUrl}/${path}`, headers, JSON.stringify(body), signal); return new Response(r.body, { status: r.status, headers: r.headers }); }
  async *parseStream(response: Response): AsyncGenerator<CodexSSEEvent> { yield* parseSSEStream(response); }
}
