import { useEffect, useRef, useState } from "preact/hooks";
import { useUiAppearance } from "../../../shared/hooks/use-ui-appearance";
export function AppearanceDrawer() {
  const input = useRef<HTMLInputElement>(null); const appearance = useUiAppearance(); const data = appearance.data; const [open, setOpen] = useState(false);
  useEffect(() => { const show = () => setOpen(true); window.addEventListener("codex:open-appearance", show); return () => window.removeEventListener("codex:open-appearance", show); }, []);
  if (!data) return null;
  if (!open) return null;
  return <><button class="appearance-backdrop" aria-label="关闭外观设置" onClick={() => setOpen(false)} /><aside class="appearance-drawer glass-surface" aria-label="外观与背景设置"><div class="flex items-center justify-between"><div><p class="text-meta uppercase tracking-[.16em] text-slate-500">APPEARANCE</p><h2 class="text-section font-semibold">外观与背景</h2></div><button class="header-appearance size-8 rounded-lg" onClick={() => setOpen(false)} aria-label="关闭">×</button></div><p class="mt-2 text-reading text-slate-500">背景保持清晰存在，组件不透明度单独控制。</p><div class="mt-5 grid gap-4"><label class="text-control">工作台不透明度 <output>{Math.round(data.panelOpacity * 100)}%</output><input class="w-full" type="range" min="0.38" max="0.82" step="0.01" value={data.panelOpacity} onInput={(e) => void appearance.update({ panelOpacity: Number((e.target as HTMLInputElement).value) })} /></label><label class="text-control">组件不透明度 <output>{Math.round(data.cardOpacity * 100)}%</output><input class="w-full" type="range" min="0.52" max="0.92" step="0.01" value={data.cardOpacity} onInput={(e) => void appearance.update({ cardOpacity: Number((e.target as HTMLInputElement).value) })} /></label><label class="text-control">背景亮度 <output>{Math.round(data.brightness * 100)}%</output><input class="w-full" type="range" min="0.35" max="1" step="0.01" value={data.brightness} onInput={(e) => void appearance.update({ brightness: Number((e.target as HTMLInputElement).value) })} /></label><label class="text-control">背景模糊 <output>{data.blurPx}px</output><input class="w-full" type="range" min="0" max="12" step="1" value={data.blurPx} onInput={(e) => void appearance.update({ blurPx: Number((e.target as HTMLInputElement).value) })} /></label></div><div class="mt-6 flex gap-2"><button class="px-3 py-2 rounded-lg text-control bg-primary-action text-white" onClick={() => input.current?.click()}>上传背景</button><input ref={input} class="hidden" type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => { const file = (e.target as HTMLInputElement).files?.[0]; if (file) void appearance.upload(file); }} /><button class="px-3 py-2 rounded-lg text-control header-appearance" onClick={() => void appearance.update({ panelOpacity: 0.70, cardOpacity: 0.74, brightness: 0.72, blurPx: 2 })}>恢复推荐值</button></div></aside></>;
}
